### ISSUE TITLE
Feature request: Automatically Apply to New Tabs

### ISSUE THREAD

**Issue by VidFerris** [dstein64/highlight#3]
Hi;
Really like this addon! I'd really like an option to automatically apply highlighting at a chosen setting to new tabs when they're opened (ideally after a custom delay, for pages that load content in via JS). Took me a while to realise that "Global Highlighting" isn't doing this, as it just applies highlighting to the currently open tabs - I thought it was malfunctioning but I'm guessing that's intended behaviour. I'd really like to be able to set the highlighting level, and then automatically apply it every time I visit a new page. Thanks again for this great tool!

**Comment by dstein64** [comment]
Hi @VidFerris. Thanks for suggesting this idea!

An _Autonomous Highlights_ option has been added to the extension. It can be enabled in the options menu, along with corresponding settings for a delay and an amount of highlighting.

Using a delay of 0 seconds worked fine in my testing. I think this is due to browsers using [heuristics](https://developer.chrome.com/extensions/content_scripts#document_idle) for when to execute the code. YMMV.

I've submitted the updated extension to Chrome, Firefox, and Edge. It has been approved for Firefox, and the review is still pending for the others (it can take up to a few days, based on prior experience). The setting requires additional permissions, requested when the functionality is enabled.

![options](https://user-images.githubusercontent.com/541289/92840686-648cd900-f3af-11ea-81ac-45a31a98a976.png)
