### ISSUE TITLE
Feature request: blocklist for pages/sites that don't benefit from autonomous highlighting

### ISSUE THREAD

**Issue by hmijail** [dstein64/highlight#4]
Pages/sites that are [mostly source code](https://github.com/dstein64/highlight/commit/e777fc825ff5c868fb456897c5f06d39a6e6c35d), or which have little text, don't benefit from autonomous highlighting. It'd be great to have a way to disable it for such pages/sites. Maybe a blocklist, or a minimum text length threshold, or maybe the importance estimation algorithm has enough information to decide when it makes no sense to highlight?

**Comment by dstein64** [comment]
@hmijail Thanks for the idea!

Cc:  @VidFerris

Blocklist support is implemented for autonomous highlighting. The list can be modified on the options page, or by adding pages and hostnames using the new context menu (screenshot below; icons are supported only on Firefox, as Chrome and Edge do not currently support context-menu icons below the top level).

In addition to URLs and hostnames, [URL match patterns](https://developer.chrome.com/extensions/match_patterns) can also be added to the blocklist.

Rather than _blocking_ autonomous highlighting on certain pages, the blocklist can alternatively be used for _allowing_ autonomous highlighting on certain pages. This is documented on the options page under _Blocklist Information > Allowing Certain Pages_.

I've submitted the updated extension to Chrome, Firefox, and Edge. It has been approved for Firefox, and the review is still pending for the others (it can take up to a few days, based on prior experience).

### Context Menu Screenshot

![screenshot](https://user-images.githubusercontent.com/541289/94378852-7e8e2180-00fa-11eb-92ad-c5eeaa5559f2.png)
